# for Linux
[target.x86_64-unknown-linux-gnu]
linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]         # lld is 2x fast than ld (default linker)
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"] # mold is 5x fast than lld

# for Windows
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
